<#
.SYNOPSIS
    Checks, updates, packs and publishes the active Chocolatey packages of this repository.

.DESCRIPTION
    Every folder that contains an update.ps1 (Chocolatey-AU) is an active package. For each one the
    script runs update.ps1, pushes the resulting .nupkg to the Chocolatey community repository and,
    at the end, commits and pushes to Git only the packages that were published successfully (a
    failed push is retried on the next run instead of being recorded as done).

.PARAMETER Package
    Only process these packages (folder names, comma separated). Default: all active packages.

.PARAMETER Force
    Pack and push the packages even when there is no new upstream version.

.PARAMETER NoPush
    Update and pack only: nothing is pushed to Chocolatey or Git and the .nupkg files are kept.

.PARAMETER NoGit
    Push to Chocolatey but do not commit/push the changes to Git.

.EXAMPLE
    .\update_all.ps1

.EXAMPLE
    .\update_all.ps1 -Package nicepage -Force
#>
[CmdletBinding()]
param(
    [string[]] $Package,
    [switch] $Force,
    [switch] $NoPush,
    [switch] $NoGit
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'  # Windows PowerShell downloads are much slower with the progress bar
$pushSource = 'https://push.chocolatey.org/'

Write-Host '========================================================'
Write-Host 'AU Maestro: Actualizacion, Push y Git Sync'
Write-Host '========================================================'
if ($Force) { Write-Host '>>> MODO FORZADO: se empaquetan y suben los paquetes aunque no haya version nueva.' -ForegroundColor Yellow }

function Invoke-Tool {
    # choco/git write progress and warnings to stderr; with 'Stop' Windows PowerShell can turn that
    # into a terminating error when the output is redirected (CI). The exit code is checked instead.
    $ErrorActionPreference = 'Continue'
    $command, $arguments = $args
    & $command @arguments
}

# Chocolatey-AU is the maintained successor of the archived AU module (same commands)
if (Get-Module -ListAvailable -Name Chocolatey-AU) {
    Import-Module Chocolatey-AU
} elseif (Get-Module -ListAvailable -Name AU) {
    Import-Module AU
    Write-Warning 'Usando el modulo AU (archivado). Recomendado: choco install chocolatey-au'
} else {
    throw 'Chocolatey-AU no esta instalado. Ejecuta: choco install chocolatey-au'
}

# Active packages = folders with an update.ps1 (deprecated packages live in .\deprecated)
$packageDirs = @(Get-ChildItem -Path $PSScriptRoot -Directory | Where-Object { Test-Path (Join-Path $_.FullName 'update.ps1') })
if ($Package) {
    # powershell -File passes "a,b" as a single string
    $Package = @($Package -split ',' | ForEach-Object Trim | Where-Object { $_ })
    $unknown = @($Package | Where-Object { $_ -notin $packageDirs.Name })
    if ($unknown) { throw "Paquete(s) desconocido(s): $($unknown -join ', '). Disponibles: $($packageDirs.Name -join ', ')" }
    $packageDirs = @($packageDirs | Where-Object Name -In $Package)
}

$report = [System.Collections.Generic.List[object]]::new()

foreach ($dir in $packageDirs) {
    $name = $dir.Name
    Write-Host "`n>>> Procesando: $name" -ForegroundColor Cyan

    $row = [pscustomobject]@{ Paquete = $name; Anterior = '?'; Nueva = '?'; Estado = 'Error' }
    $updated = $false
    # Snapshot of the package folder: if the new version is not published, AU's changes are rolled back
    # so the next run detects the update again (edits made before this run are part of the snapshot)
    $snapshot = Join-Path ([System.IO.Path]::GetTempPath()) "au-snapshot-$name"
    $hasSnapshot = $false
    Push-Location $dir.FullName
    try {
        Remove-Item -Path $snapshot -Recurse -Force -ErrorAction SilentlyContinue
        Copy-Item -Path $dir.FullName -Destination $snapshot -Recurse -Force  # -Force: hidden files too
        $hasSnapshot = $true

        Remove-Item -Path *.nupkg -ErrorAction SilentlyContinue
        # AU hooks are global functions: a package must not inherit the hooks of the previous one
        Remove-Item -Path Function:\au_BeforeUpdate, Function:\au_AfterUpdate -ErrorAction SilentlyContinue

        $row.Anterior = ([xml](Get-Content -Path "$name.nuspec" -Raw)).package.metadata.version
        $row.Nueva = $row.Anterior

        # update.ps1 returns the AUPackage object (or 'ignore') as its last output
        $result = & .\update.ps1 | Select-Object -Last 1
        $updated = ($result -isnot [string]) -and $result.Updated
        if ($updated) {
            $row.Nueva = $result.RemoteVersion
            Write-Host ">>> Actualizacion detectada: $name v$($row.Anterior) -> v$($row.Nueva)" -ForegroundColor Green
        }

        if (-not ($updated -or $Force)) {
            $row.Estado = 'Al dia'
        } else {
            # Files generated by update.ps1 (e.g. Thunderbird's checksums.txt) must exist before packing
            $missing = @(Select-String -Path 'tools\*.ps1' -Pattern "Join-Path \`$toolsDir '([^']+)'" -AllMatches |
                ForEach-Object { $_.Matches } | ForEach-Object { $_.Groups[1].Value } |
                Where-Object { -not (Test-Path (Join-Path 'tools' $_)) } | Sort-Object -Unique)
            if ($missing) { throw "Faltan archivos generados por update.ps1 ($($missing -join ', ')): no se publica un paquete roto." }

            # AU already packed the package when it updated it (one .nupkg per updated stream);
            # otherwise (forced) pack it now
            $nupkgs = @(Get-ChildItem -Path *.nupkg)
            if (-not $nupkgs) {
                Invoke-Tool choco pack --limit-output
                if ($LASTEXITCODE -ne 0) { throw "choco pack fallo (codigo $LASTEXITCODE)" }
                $nupkgs = @(Get-ChildItem -Path *.nupkg)
            }
            $row.Nueva = ($nupkgs | ForEach-Object { $_.BaseName.Substring($name.Length + 1) }) -join ', '

            if ($NoPush) {
                $row.Estado = 'Empaquetado'
            } else {
                $pushFailed = $false
                foreach ($nupkg in $nupkgs) {
                    $pushArgs = @('push', $nupkg.FullName, '--source', $pushSource, '--limit-output')
                    if ($env:CHOCO_API_KEY) { $pushArgs += @('--api-key', $env:CHOCO_API_KEY) }
                    Invoke-Tool choco @pushArgs
                    if ($LASTEXITCODE -ne 0) { $pushFailed = $true }
                }
                $row.Estado = if ($pushFailed) { 'Push fallido' } elseif ($updated) { 'Actualizado' } else { 'Forzado' }
            }
        }
    } catch {
        Write-Host "[ERROR] $name : $_" -ForegroundColor Red
    } finally {
        if (-not $NoPush) { Remove-Item -Path *.nupkg -ErrorAction SilentlyContinue }
        Pop-Location
        if ($hasSnapshot -and -not $NoPush -and $row.Estado -in 'Error', 'Push fallido') {
            Get-ChildItem -Path $dir.FullName -Force | Remove-Item -Recurse -Force
            Copy-Item -Path (Join-Path $snapshot '*') -Destination $dir.FullName -Recurse -Force
            Write-Host "[ERROR] $name no se publico: se restauraron sus archivos para reintentarlo en la proxima ejecucion." -ForegroundColor Red
        }
        Remove-Item -Path $snapshot -Recurse -Force -ErrorAction SilentlyContinue
        # Installers downloaded by AU to calculate checksums (can be hundreds of MB)
        Remove-Item -Path (Join-Path $env:TEMP "chocolatey\$name") -Recurse -Force -ErrorAction SilentlyContinue
    }
    $report.Add($row)
}

Write-Host "`n========================================================"
Write-Host '                RESUMEN DE ACTUALIZACIONES'
Write-Host '========================================================'
$report | Format-Table -AutoSize | Out-String -Width 200 | Write-Host

# --- GIT SYNC: only packages that reached Chocolatey (unpublished ones were restored above) ---
function Sync-GitRemote([bool] $HasNewCommit) {
    # Pushes every local commit, including one left behind by a previous run whose push failed.
    # If the remote moved on meanwhile (e.g. another run), rebase onto it and retry once.
    $ahead = Invoke-Tool git -C $PSScriptRoot rev-list --count '@{u}..HEAD' 2>$null
    if ($LASTEXITCODE -ne 0) {
        # No upstream branch: only publish the branch if this run committed something to it
        if (-not $HasNewCommit) { return $true }
        $branch = Invoke-Tool git -C $PSScriptRoot symbolic-ref --short -q HEAD
        if (-not $branch) { Write-Host '[ERROR] HEAD desconectado (detached): no se puede hacer push.' -ForegroundColor Red; return $false }
        Invoke-Tool git -C $PSScriptRoot push --set-upstream origin $branch | Out-Host
        return ($LASTEXITCODE -eq 0)
    }
    if (-not ($ahead -as [int])) { return $true }
    Invoke-Tool git -C $PSScriptRoot push | Out-Host
    if ($LASTEXITCODE -ne 0) {
        Invoke-Tool git -C $PSScriptRoot pull --rebase --autostash | Out-Host
        if ($LASTEXITCODE -eq 0) { Invoke-Tool git -C $PSScriptRoot push | Out-Host }
    }
    return ($LASTEXITCODE -eq 0)
}

if ($NoPush -or $NoGit) {
    Write-Host '>>> Git Sync omitido (-NoPush / -NoGit).' -ForegroundColor Gray
} else {
    # Forced pushes count too (e.g. a fix version edited by hand), but only if their folder has changes
    $published = @($report | Where-Object { $_.Estado -eq 'Actualizado' -or
        ($_.Estado -eq 'Forzado' -and (Invoke-Tool git -C $PSScriptRoot status --porcelain $_.Paquete)) })
    $gitOk = $true
    if ($published) {
        Write-Host '>>> Sincronizando cambios con Git...' -ForegroundColor Cyan
        $paths = @($published.Paquete)
        $message = 'chore: automated update of ' + (($published | ForEach-Object { "$($_.Paquete) v$($_.Nueva)" }) -join ', ')
        # Commit only the published packages ("--only"), never other changes the user had already staged
        Invoke-Tool git -C $PSScriptRoot add @paths
        if ($LASTEXITCODE -eq 0) { Invoke-Tool git -C $PSScriptRoot commit --only -m $message @paths }
        $gitOk = ($LASTEXITCODE -eq 0)
    }
    if ($gitOk) { $gitOk = Sync-GitRemote -HasNewCommit ($published.Count -gt 0) }

    if (-not $gitOk) {
        Write-Host '[ERROR] Git Sync fallo: los paquetes ya estan en Chocolatey; revisa el commit/push pendiente (se reintenta en la proxima ejecucion).' -ForegroundColor Red
        $report.Add([pscustomobject]@{ Paquete = 'git'; Anterior = ''; Nueva = ''; Estado = 'Error' })
    } elseif ($published) {
        Write-Host '>>> Git Sync completado.' -ForegroundColor Green
    } else {
        Write-Host '>>> No hay cambios que sincronizar en Git.' -ForegroundColor Gray
    }
}

$failed = @($report | Where-Object Estado -In 'Error', 'Push fallido')
exit $(if ($failed) { 1 } else { 0 })
