name: Auto Update Packages

on:
#  schedule:
#    - cron: '0 5 * * *' # Corre todos los días a las 5:00 AM (UTC)
  workflow_dispatch: # Te permite agregar un botón en GitHub para correrlo cuando quieras

jobs:
  update-repo:
    runs-on: windows-latest
    permissions:
      contents: write # Permiso para que el bot pueda hacer push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Chocolatey Automatic Updater (AU)
        shell: powershell
        run: |
          Install-Module au -Scope CurrentUser -Force

      - name: Set Chocolatey API Key
        shell: powershell
        run: |
          choco apikey add -k ${{ secrets.CHOCO_API_KEY }} -s https://push.chocolatey.org/

      - name: Run Update Script
        shell: cmd
        run: |
          update_all.bat

      - name: Commit and Push Changes (Sync)
        shell: powershell
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          
          # Verificamos si quedaron cambios pendientes después del script
          $changes = git status --porcelain
          if ($changes) {
            git commit -m "chore: Auto-update package versions via AU"
            git push
          } else {
            Write-Host "Revisión completada: El repositorio ya está sincronizado."
          }
